### ISSUE TITLE
Not working on Silksong suddenly.

### ISSUE THREAD

**Issue by teh-ches-noddle** [BepInEx/BepInEx#1169]
### What happened?

Ok so the last two days I've been using BepInEx to use the Silksong Customizer mod.  That is the only mod I have used with it and it worked just fine up till this morning.  I turn off my PC each night and when I turn it on and start up Silksong I notice the skin I'm using isn't there.  Then I also notice I can't open the BepInEx menu with F1.  So I remove the mod and try launching the game again with only BepInEx, still nothing.  So I suspect it's BepInEx not working.

I've tried just about everything I can think of and here's a list of everything I've done.
-Checking if Windows updated in the night (it did not, it's the same version as it was when BepInEx worked)
-Checking if Silksong updated (It also has not, same version as when BepInEx worked)
-Restarting my PC
-Uninstalling BepInEx and reinstalling it
-Uninstalling BepInEx and then uninstalling Silksong and reinstalling both, launching Silksong once before installing BepInEx again.
-Trying the Vortex mod launcher and using BepInEx through there. (Saw a comment on Nexus that said it worked through the launcher)
-Deleting Vortex and trying again manually by using specifically the version for Silksong on thunderstore.
-Reinstalling it several times seeing each time if Launching Silksong through my desktop shortcut or steam directly would be the solution since the log files said it wasn't launched through steam.

Currently, I have the version of BepInEx installed manually through this link: https://thunderstore.io/c/hollow-knight-silksong/p/BepInEx/BepInExPack_Silksong/  but it still will not show any sign that it's working.  When launching directly through steam after reinstalling BepInEx it doesn't create a log and the only folders in BepInEx are the ones it starts with when downloaded (Config, core and plugins).  It only seems to created the log output alongside the cache and patchers folders when launched through my desktop shortcut.  However, it says in the log output "Application was not launched through Steam! Shutting down..." (through the my desktop shortcut still opens it through steam?  It's just not hitting the play button in the steam app.)  The log output attached it the log it creates when it does this.
If I try launching through steam or my desktop after, nothing happens.  The log isn't updated and Silksong remains Vanilla.

### BepInEx Distribution

3rd party distribution

### Log outputs

```txt
[Error  :   BepInEx] Unable to start Unity log writer
[Message:   BepInEx] BepInEx 5.4.23.3 - Hollow Knight Silksong (2025-09-20 12:00:58 PM)
[Info   :   BepInEx] Running under Unity v6000.0.50.3512832
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.3]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
[Error  : Unity Log] Application was not launched through Steam! Shutting down...
[Info   : Unity Log] Steam initializing
[Error  : Unity Log] Steam failed to initialize
[Info   : Unity Log] Selecte
```

### Environment

```markdown
- OS: Windows 11
- BepInEx: 5.4.23.3
- Game: Hollow Knight: Silksong
```

**Comment by toebeann** [comment]
Double check that the desktop shortcut is in fact launching it through Steam, i.e. that it's set up to run Steam.exe with arguments or that it's set up to open a steam:// protocol URL. Otherwise, it's the same as running the .exe directly.

However, it could just be that Steam API has failed to inject. This happens sometimes, and is usually fixed by restarting Steam itself or the computer, and ensuring you _always_ launch the game through Steam, as not doing that can trigger the glitch. It can also be triggered by running _other_ Steam games via their .exe, or running pirated Steam games.

If restarting Steam or your computer then ensuring you are running directly via Steam doesn't help, then you have something else at play. But first we should rule that out.

**Comment by teh-ches-noddle** [comment]
Ok I restarted steam first and launched the game through the steam app itself and it gave me a different Log Output.  Through it still isn't bringing up the menu when pressing F1 in game.  

Here's the log it gave me this time:

[Error  :   BepInEx] Unable to start Unity log writer
[Message:   BepInEx] BepInEx 5.4.23.3 - Hollow Knight Silksong (2025-09-20 12:00:58 PM)
[Info   :   BepInEx] Running under Unity v6000.0.50.3512832
[Info   :   BepInEx] CLR runtime version: 4.0.30319.42000
[Info   :   BepInEx] Supports SRE: True
[Info   :   BepInEx] System platform: Bits64, Windows
[Message:   BepInEx] Preloader started
[Info   :   BepInEx] Loaded 1 patcher method from [BepInEx.Preloader 5.4.23.3]
[Info   :   BepInEx] 1 patcher plugin loaded
[Info   :   BepInEx] Patching [UnityEngine.CoreModule] with [BepInEx.Chainloader]
[Message:   BepInEx] Preloader finished
[Message:   BepInEx] Chainloader ready
[Message:   BepInEx] Chainloader started
[Info   :   BepInEx] 0 plugins to load
[Message:   BepInEx] Chainloader startup complete
[Info   : Unity Log] Steam initializing
[Info   : Unity Log] Steam logged in as teh_ches_noddle
[Info   : Unity Log] Selected online subsystem SteamOnlineSubsystem
[Info   : Unity Log] Steam stats received.
[Info   : Unity Log] Discovered supported languages: DE, EN, ES, FR, IT, JA, KO, PT, RU, ZH
[Info   : Unity Log] Loaded saved language code 'EN'
[Info   : Unity Log] Restored language code 'EN'
[Error  : Unity Log] Couldn't find a Game Manager, make sure one exists in the scene.
[Error  : Unity Log] Couldn't find GameCameras, make sure one exists in the scene.
[Error  : Unity Log] Couldn't find GameCameras, make sure one exists in the scene.
[Error  : Unity Log] Couldn't find a Game Manager, make sure one exists in the scene.
[Info   : Unity Log] Loaded saved language code 'EN'
[Info   : Unity Log] Restored language code 'EN'
[Warning: Unity Log] MenuButton missing flashEffect!
[Info   : Unity Log] Making UI menu lean.
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Audio Player Actor Distant V2(Clone)).
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Audio Player Actor Distant V2(Clone)).
[Warning: Unity Log] Only custom filters can be played. Please add a custom filter or an audioclip to the audiosource (Audio Player Actor Distant V2(Clone)).
[Warning: Unity Log] Converting Vertex Colors from Color32 to Color.
[Warning: Unity Log] Converting Vertex Colors from Color32 to Color.
[Warning: Unity Log] Converting Vertex Colors from Color32 to Color.
[Info   : Unity Log] Loaded saved language code 'EN'
[Info   : Unity Log] Restored language code 'EN'

**Comment by toebeann** [comment]
You don't have the configuration manager plugin installed in that log, so of course pressing F1 does nothing.

**Comment by toebeann** [comment]
The menu that opens when you press F1 is not part of BepInEx itself, it's a plugin called Configuration Manager that you must install separately :)

**Comment by teh-ches-noddle** [comment]
Ah, weird cause it was in the other version I had installed yesterday and worked.  I don't need the config manager tho so that's fine.  Just checked with skin customizer and it works fine now so I guess it was just cause I wasn't always launching directly through steam.  (though I did that yesterday too and it still worked fine??)  

Thanks for the help :)

**Comment by toebeann** [comment]
> Ah, weird cause it was in the other version I had installed yesterday and worked.

You probably had downloaded a third-party pack of BepInEx that included it, but the pack on thunderstore does not :)

Glad you got it working. If you want desktop shortcuts which are compatible with BepInEx, go to the game in your steam library and right click it (or click the cog) and there should be an option to make a desktop shortcut. This will always generate a shortcut that launches the game "the right way."

Have fun :)
